# Generated by Django 5.0.1 on 2024-05-04 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('phone_number', models.IntegerField()),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Descriptions_about_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('who', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Student', 'Student')], default='Student', max_length=250)),
                ('descriptions', models.TextField()),
                ('photo', models.ImageField(upload_to='edu_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('teacher_photo', models.ImageField(upload_to='edu_images/')),
                ('which_subjects', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='We_have_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Our_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_students', models.IntegerField()),
                ('course_photo', models.ImageField(upload_to='edu_images/')),
                ('about_course', models.TextField()),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.teachers')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.we_have_courses')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolling_to_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('surname', models.CharField(max_length=225)),
                ('phone_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('selected_courses', models.ManyToManyField(to='education.we_have_courses')),
            ],
        ),
    ]
