# Generated by Django 5.0.1 on 2024-05-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolling_to_course',
            name='selected_courses',
        ),
        migrations.AddField(
            model_name='enrolling_to_course',
            name='selected_courses',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
