# Generated by Django 5.0.1 on 2024-05-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_enrolling_to_course_selected_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='message',
            field=models.CharField(max_length=225),
        ),
    ]
